/** Cloudflare Worker backend for AI Math Error Note.
 * Set OPENAI_API_KEY as a Worker secret.
 * Deploy this folder with: wrangler deploy
 */
const json=(o,s=200)=>new Response(JSON.stringify(o),{status:s,headers:{'content-type':'application/json','access-control-allow-origin':'*','access-control-allow-headers':'content-type','access-control-allow-methods':'POST,OPTIONS'}});
const instruction=`You are an expert elementary/middle-school math worksheet analyzer. Analyze every uploaded graded worksheet image. Identify individual printed problems, student-written answers, teacher grading marks (red/blue/black circles, X, check marks, scores, comments), and whether each problem is wrong. Return STRICT JSON only with {"total":number,"wrong":number,"items":[{"problemNumber":string,"wrong":boolean,"studentAnswer":string,"correctAnswer":string,"problemText":string,"reason":string,"solution":string,"bbox":[x,y,w,h]}]}. bbox is normalized 0..1 coordinates for the printed problem area in the source image. Do not treat teacher marks as part of the printed problem. If correctness cannot be determined confidently, set wrong=false.`;
async function responses(env,content){const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Authorization':`Bearer ${env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:env.VISION_MODEL||'gpt-6-luna',input:[{role:'user',content:[{type:'input_text',text:instruction},...content]}]})});if(!r.ok)throw new Error(await r.text());const d=await r.json();return d.output_text||''}
async function editImage(env,dataUrl,prompt){const [head,b64]=dataUrl.split(',');const mime=(head.match(/data:([^;]+)/)||[])[1]||'image/jpeg';const bytes=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));const blob=new Blob([bytes],{type:mime});const form=new FormData();form.append('model',env.IMAGE_MODEL||'gpt-image-2');form.append('image[]',blob,'problem.png');form.append('prompt',prompt);form.append('size','auto');const r=await fetch('https://api.openai.com/v1/images/edits',{method:'POST',headers:{'Authorization':`Bearer ${env.OPENAI_API_KEY}`},body:form});if(!r.ok)throw new Error(await r.text());const d=await r.json();return d.data?.[0]?.b64_json?`data:image/png;base64,${d.data[0].b64_json}`:null}
function cropDataUrl(dataUrl,bbox){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{const c=document.createElement('canvas');const [x,y,w,h]=bbox;c.width=Math.max(1,Math.round(im.width*w));c.height=Math.max(1,Math.round(im.height*h));c.getContext('2d').drawImage(im,Math.round(im.width*x),Math.round(im.height*y),c.width,c.height,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.92))};im.onerror=reject;im.src=dataUrl})}
async function handle(req,env){if(req.method==='OPTIONS')return json({ok:true});if(req.method!=='POST')return json({error:'POST only'},405);const body=await req.json();const images=body.images||[];if(!env.OPENAI_API_KEY)return json({error:'OPENAI_API_KEY is not configured'},500);if(!images.length)return json({error:'No images'},400);
const content=images.map((u,i)=>({type:'input_image',image_url:u,detail:'high'}));let raw=await responses(env,content);raw=raw.replace(/^```json\s*|\s*```$/g,'').trim();let parsed;try{parsed=JSON.parse(raw)}catch{throw new Error('AI returned invalid JSON: '+raw.slice(0,500))}
const items=parsed.items||[];const out=[];for(let i=0;i<items.length;i++){const x=items[i];if(!x.wrong)continue;const page=images[Math.min(Number(x.page||0),images.length-1)];let cleaned=null;try{let crop=page;if(Array.isArray(x.bbox)&&x.bbox.length===4)crop=await cropDataUrl(page,x.bbox);cleaned=await editImage(env,crop,`Preserve the printed math problem exactly. Remove ONLY all student handwriting, handwritten answers, teacher grading marks, circles, check marks, X marks, scores, comments, and colored pen/pencil annotations. Reconstruct the paper background naturally. Do not alter, rewrite, solve, translate, or change any printed text, numbers, symbols, diagrams, or answer choices. Output a clean worksheet problem image.`)}catch(e){cleaned=null}out.push({...x,originalImage:page,cleanedImage:cleaned||page})}
return json({total:parsed.total||items.length,wrong:out.length,results:out});}
export default {async fetch(req,env){try{return await handle(req,env)}catch(e){return json({error:e.message||String(e)},500)}}};
